services:
  app:
    build: .
    ports:
      - "${PORT}:8080"
    environment:
      - NODE_ENV=${MODE}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules